{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devops-practical.fullname" . }}-mongodb
type: Opaque
stringData:
  mongodb_url: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ include "devops-practical.fullname" . }}-mongodb:{{ .Values.mongodb.servicePort }}/{{ .Values.mongodb.database }}?authSource=admin"
{{- end }}

