{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "devops-practical.fullname" . }}-mongodb
spec:
  serviceName: {{ include "devops-practical.fullname" . }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devops-practical.name" . }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "devops-practical.name" . }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - name: mongo
              containerPort: {{ .Values.mongodb.servicePort }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.username | quote }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.password | quote }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.database | quote }}
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.mongodb.persistence.storageClassName }}
        storageClassName: {{ .Values.mongodb.persistence.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
{{- end }}

